[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "AWSGlueDataplanePython"
version = "5.1.0"
description = "AWS Glue Python library for local ETL script development"
readme = "README.md"
license = {file = "LICENSE.txt"}
requires-python = ">=3.10"

[tool.setuptools.packages.find]
include = ["awsglue*"]
